fos_rest:
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    allowed_methods_listener: true
    routing_loader: false
    body_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    view:
        view_response_listener: 'force'
        formats:
            json: true
    exception:
        enabled: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: [ 'json' ], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
