nelmio_api_doc:
    documentation:
        info:
            title: Media data API
            description: API allows to query media metadata by file name
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
