parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    anilist.graphql.client:
        class: GraphQL\Client
        factory: [ '@App\AnimeData\Anilist\Client\GraphqlClientFactory', 'buildClient' ]
        arguments:
            $url: '%env(resolve:APP_ANILIST_GRAPHQL_URL)%'

    App\AnimeData\Anilist\Client\GetMediaRequest:
        arguments:
            $client: '@anilist.graphql.client'
